### PR TITLE
Remove tile extension restriction

### PR DESCRIPTION
**Pull request by lilleyse**
Addresses https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/90#issuecomment-246207288

Cesium Implementation: https://github.com/AnalyticalGraphicsInc/cesium/pull/5206

### CODE REVIEW

**Comment by pjcozzi** [comment]
Each tile format spec (including the PR for vector tiles) should be updated to explicitly mention it is optional; validation implementations ignore it and use `magic`.

For example: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/Instanced3DModel#file-extension

**Comment by lilleyse** [comment]
Updated, if the wording seems fine I'll update vector tiles.

**Comment by pjcozzi** [comment]
Looks good, please update vector tiles.

Leaving #90 open for its other topics.

**Comment by lilleyse** [comment]
Updated there.

**Pull request merged**
