### PR TITLE
Schema for tiles.json

### LINKED ISSUE #3: JSON schema for tiles.json
To be more complete and rigorous than just the example in README.md.

### PR DESCRIPTION
**Pull request by pjcozzi**
Fixes #3 and #18.

@lilleyse can you do a technical review?

@slchow this doesn't need a copyedit; we'll copyedit the generated reference doc like we did for glTF when it is ready.

### CODE REVIEW

**Comment by lilleyse** [comment]
I see some typos, but besides that the tech seems fine to me. The `properties` area in `tiles.schema.json` looks confusing but I assume it generates correctly.

**Comment by pjcozzi** [comment]
Can you comment on or fix the typos?

**Comment by pjcozzi** [comment]
> The properties area in tiles.schema.json looks confusing but I assume it generates correctly.

Yes, that is standard for a dictionary object.  We do it all the time in the JSON schema for glTF and CZML.

**Comment by lilleyse** [comment]
I made the small typo changes.

**Comment by pjcozzi** [comment]
Looks good, thanks.  Is this ready?

**Comment by lilleyse** [comment]
Sorry for the delay, yes this is ready.

**Pull request merged**
