### PR TITLE
Change equality comparisons to == and !=

### PR DESCRIPTION
**Pull request by lilleyse**
Related to this discussion: https://github.com/AnalyticalGraphicsInc/cesium/pull/4336#issuecomment-252718422

>If we decide to be loose about type comparisons in the JS implementation we may also want to change === to == to force casting. Right now a style with 5 < "6" would return true but 5 === "5" would be false.

### CODE REVIEW

**Comment by pjcozzi** [comment]
I think I understand that you want to add `==` and `!=` so that they behave similar to `<` and friends with type coercion, but why are we removing the JavaScript best practice `===` and `!==` operators?  Because they can't be implemented with the GLSL transpiler?  If so, please explain.

**Comment by lilleyse** [comment]
Oh I was thinking we would not support both == and === at the same time, but that's definitely doable.

**Comment by pjcozzi** [comment]
OK, let's do it, thanks.

**Comment by pjcozzi** [comment]
@lilleyse can you please update this PR and also update the styling spec to include changes needed for point clouds, e.g., `pointSize` in this PR or a new one?

**Comment by lilleyse** [comment]
Updated. I'll open a new PR for the other styling and point cloud changes.

**Comment by pjcozzi** [comment]
Looks good.

**Pull request merged**
