### PR TITLE
Merge 1.0 branch into master

### PR DESCRIPTION
**Pull request by lilleyse**
The updates here have already been reviewed, mostly in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/308. The `1.0` changes should be ready to merge into `master` now.

Right after merging:
* [ ] Fix broken specification links. I did a search for `3d-tiles/tree/master/` and `3d-tiles/tree/1.0/` and these projects had links:
    * [ ] cesium
    * [ ] cesium.com
    * [ ] cesiumjs.org

@pjcozzi @ggetz is there anything left to add here?

### CODE REVIEW

**Comment by ggetz** [comment]
List looks good.

Maybe a final copy edit if @slchow has the time, but I don't think it's necessary in order to merge this.

**Comment by ggetz** [comment]
Only other thing I can think of is if we want to park current master in a branch because it has the start of some additional tile formats like VectorData, unless we want to carry over those changes here.

**Comment by ggetz** [comment]
Disregard my above comment, I see the `next` branch and https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/328

**Comment by lilleyse** [comment]
If not a branch, maybe a tag for the current master so we can reference it later as needed.

**Comment by lilleyse** [comment]
I pushed a `0.0` tag.

**Comment by slchow** [comment]
I could copyedit, but it would realistically be the end of next week at least before I could get to it. @lilleyse Do you want me to look it over?

**Comment by lilleyse** [comment]
I think it's fine to merge without a copyedit.

**Comment by ggetz** [comment]
@lilleyse I think we should also merge https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/329 before merging this.

**Comment by ggetz** [comment]
Fixed a few typos and published a new PDF. I think this should be ready to go.

**Comment by lilleyse** [comment]
Otherwise looks great!

**Comment by ggetz** [comment]
Thanks @lilleyse! Made the fixes in the PDF, and now reference the tag instead of the branch.

I don't see any `1.0` tag however, should we create once we merge this PR?

**Comment by lilleyse** [comment]
Oh I was mixing up the tags...

But yeah, keep the `0.0` tag as-is and add a `1.0` rag right after merging this, and point to the `1.0` tag in the PDF (the link in the PDF should be `https://github.com/AnalyticalGraphicsInc/3d-tiles/releases/tag/1.0`).

It also looks like some files got added accidentally to the last commit.

**Comment by ggetz** [comment]
Sounds good :+1: 

Whoops, removed the extra files, and updated.

**Comment by lilleyse** [comment]
In addition to creating the tag, could you also fix the now-broken spec links mentioned in the PR description?

That looks like everything. Thanks @ggetz!

**Pull request merged**
