### PR TITLE
Update pnts tile format spec to include batch table

### PR DESCRIPTION
**Pull request by pjcozzi**
https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/pnts/TileFormats/Points

Add notes to keep it up-to-date with https://github.com/AnalyticalGraphicsInc/cesium/pull/4112

These are just notes; there will be more words when we flush out the spec.

Part of #22.

### CODE REVIEW

**Comment by lilleyse** [comment]
The image has a colors[] at the end still.

**Comment by lilleyse** [comment]
Maybe worth adding that a default color will be used if no color semantics are present.

**Comment by pjcozzi** [comment]
> The image has a colors[] at the end still.

Good eye, updated.

**Comment by pjcozzi** [comment]
> Maybe worth adding that a default color will be used if no color semantics are present.

Yes, updated.

This is ready.

**Comment by lilleyse** [comment]
Did you want to update the picture considering https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/103? I'm going to make the change in Cesium.

**Comment by pjcozzi** [comment]
Updated

**Comment by lilleyse** [comment]
I merged this.. but is the "4 byte aligned array buffer" comment needed anymore?

**Comment by pjcozzi** [comment]
It is implicit given the 28-byte header, but I still think it is good to be precise and it may be needed depending on the final format.

**Pull request merged**
