### PR TITLE
Added Section for Regular Expressions

### PR DESCRIPTION
**Pull request by ggetz**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks good!

Just curious, why the limitation?

> All arguments must be literals, not expressions.

In general, moving forward, we'll want to be able to pass expressions to functions, e.g., 
```
color.darken(${amount})
```

**Comment by ggetz** [comment]
I mentioned it briefly in my PR. Basically if it's not a literal, it will be have to be evaluated at runtime, and I thought in pretty much all cases the regex will not be stored in a property or constructed with an expression, so we can save the extra computation time. 

If desired, I can add passing expressions to the regExp constructor.

**Comment by pjcozzi** [comment]
> If desired, I can add passing expressions to the regExp constructo

Let's do it; otherwise, it is awkward that, for example, we can pass expressions to colors but not regexps.  Think about this as if it were JavaScript.

We can, of course, optimize the case if a literal is passed to regexp.  This is probably a good one to do right away.

**Comment by ggetz** [comment]
OK, I'll make that change.

**Comment by ggetz** [comment]
I opened a PR with the implementation changes, and made the correction to the spec. I also fixed the capitalization of the `regExp` function in the spec.

**Comment by pjcozzi** [comment]
:+1:

**Pull request merged**
