### PR TITLE
Added abs function

### PR DESCRIPTION
**Pull request by lilleyse**
@pjcozzi 

Cesium implementation: https://github.com/AnalyticalGraphicsInc/cesium/pull/4545

### CODE REVIEW

**Comment by pjcozzi** [comment]
Part of #2

**Comment by pjcozzi** [comment]
In GLSL, `abs` takes `genType`, https://www.opengl.org/sdk/docs/man4/html/abs.xhtml, so, for example, it works with vectors.

Do we want to do that now or do you want to start with just scalars for this and similar functions?

**Comment by pjcozzi** [comment]
When you open a PR, please include a direct link to the part of the spec updated, e.g., in this case: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/abs/Styling#built-in-functions

CC @leesafini @Dylan-Brown

**Comment by pjcozzi** [comment]
Add some intro text to the built-ins section, and also a sentence or two to https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/abs/Styling#overview

**Comment by lilleyse** [comment]
> In GLSL, abs takes genType, https://www.opengl.org/sdk/docs/man4/html/abs.xhtml, so, for example, it works with vectors.

> Do we want to do that now or do you want to start with just scalars for this and similar functions?

Maybe wait until vectors are in the spec.

**Comment by pjcozzi** [comment]
> Maybe wait until vectors are in the spec.

OK, please add to the roadmap, #2.

**Comment by lilleyse** [comment]
> OK, please add to the roadmap, #2.

Done

**Comment by lilleyse** [comment]
Ready for another look.

**Pull request merged**
